#!/bin/sh

: '
ACPI replacement
Written by Darth Venom and Tobi Emotic
< = >
'
if [ $1 -z ]; then
	x=`cat /sys/class/power_supply/BAT0/capacity`;
	echo "$x%";
	exit;
else
	echo This program does not take any argument.;
fi
