#!/usr/bin/env python3

#brainfuck diagrams
from typing import List
from token import tokenize
import sys

class MemTable:
    def __init__(self):
        self.A = []
        self.P = 0
        self.S = ""
        self.W = False
        self.T = ""
        self.S1 = True
        self.ST = False

    def IMB(self) -> str:
        MB = input("memblocks> ")
        if not MB.isdigit():
            print("mem error.")
            exit()
        return MB
    def CMB(self, x: str) -> None:
        self.A = []
        for i in range(int(x)):
            self.A.append(0)
    def PMB(self) -> None:
        S = ""
        for i in self.A:
            S += "[{}]".format(i)
        print(S)
    def SWB(self, x: str) -> None:
        x = x.replace("#", "")
        L = tokenize(x)
        if L == []:
            return ""
        if L[0] == "Pmemblocks=":
            if L[1] == "1":
                self.S1 = True
            if L[1] == "0":
                self.S1 = False
            else:
                return ""
        else:
            return ""
    def WMB(self, x: List) -> None:
        while self.A[self.P] != 0:
            for i in x:
                if i == ']':
                    self.W = False
                    self.WMB(self.T)
                    continue
                if self.W == True:
                    self.T += i
                    continue
                if i == '+':
                    if self.A[self.P] == 256:
                        continue
                    self.A[self.P] += 1
                    continue
                if i == '-':
                    if self.A[self.P] == 0:
                        continue
                    self.A[self.P] -= 1
                    continue
                if i == '<':
                    if self.P == 0:
                        continue
                    self.P -= 1
                    continue
                if i == '>':
                    if self.P == int(MB)-1:
                        continue
                    self.P += 1
                    continue
                if i == '.':
                    sys.stdout.write(chr(self.A[self.P]))
                    continue
                if i == ',':
                    I = input()
                    self.A[self.P] = ord(I[0])
                    continue
                if i == '[':
                    self.W = True
                    continue

if len(sys.argv) > 1 and sys.argv[1] == '-i':
    M = MemTable()
    MB = M.IMB()
    M.CMB(MB)
    M.PMB()

    while True:
        B = input("code> ")
        M.S = ""
        M.W = False
        M.T = ""
        for i in B:
            if M.ST:
                if i == '#':
                    M.ST = False
                    M.SWB(M.T)
                    M.T = ""
                    continue
                M.T += i
                continue
            if i == '#':
                M.ST = True
                continue
            if i == ']':
                M.W = False
                M.WMB(M.T)
                M.T = ""
                continue
            if M.W:
                M.T += i
                continue
            if i == '*':
                MB = M.IMB()
                M.CMB(MB)
                continue
            if i == '+':
                M.A[M.P] += 1
                continue
            if i == '-':
                if M.A[M.P] == 0:
                    continue
                M.A[M.P] -= 1
                continue
            if i == '<':
                if M.P == 0:
                    continue
                M.P -= 1
                continue
            if i == '>':
                if M.P == int(MB)-1:
                    continue
                M.P += 1
                continue
            if i == '.':
                sys.stdout.write(chr(M.A[M.P]))
                continue
            if i == ',':
                I = input()
                M.A[M.P] = ord(I[0])
                continue
            if i == '[':
                M.W = True
                continue
        if M.S1:
            M.PMB()

if len(sys.argv) > 1:
    M = MemTable()
    MB = 50
    M.CMB(MB)
    M.S1 = False
    F = open(sys.argv[1], 'r')
    LIN = F.readlines(); F.seek(0)

    for B in LIN:
        M.S = ""
        M.W = False
        M.T = ""
        for i in B:
            if i == ']':
                M.W = False
                M.WMB(M.T)
                M.T = ""
                continue
            if M.W:
                M.T += i
                continue
            if i == '+':
                M.A[M.P] += 1
                continue
            if i == '-':
                if M.A[M.P] == 0:
                    continue
                M.A[M.P] -= 1
                continue
            if i == '<':
                if M.P == 0:
                    continue
                M.P -= 1
                continue
            if i == '>':
                if M.P == int(MB)-1:
                    continue
                M.P += 1
                continue
            if i == '.':
                sys.stdout.write(chr(M.A[M.P]))
                continue
            if i == ',':
                I = input()
                M.A[M.P] = ord(I[0])
                continue
            if i == '[':
                M.W = True
                continue
        if M.S1:
            M.PMB()
