#!/usr/bin/env bash

: '
		Eash
	Written by Darth Venom
		< = >
'
echo;

#colores
red="\033[1;31m";
green="\033[1;32m";
yellow="\033[1;33m";
blue="\033[1;34m";
purple="\033[1;35m";
light="\033[1;36m";
white="\033[1;37m";
nml="\033[0m";

#link al directorio inter en Github.
inter="https://raw.githubusercontent.com/VENOM-InstantDeath/hkprogs/master/utils/eash/inter"

if [ $PWD != $(dirname $0) ]; then

	printf "$red""Cambiando directorio a $(dirname $0)..""$nml\n";
	cd $(dirname $0);

fi

######################################Fase de Chequeo######################################

######################################Chequeo de dependencias##############################

deparr=(0 0 0 0 0)
printf "Chequeando dependencias...\n"
which ls &> /dev/null
deparr[0]=$?
which python3 &> /dev/null
deparr[1]=$?
which git &> /dev/null
deparr[2]=$?
which figlet &> /dev/null
deparr[3]=$?
which wget &> /dev/null
deparr[4]=$?

if [ ${deparr[0]} -ne 0 ]; then printf "$red""El programa which no está instalado y es necesario. Reinstala y vuelve a ejecutar.""$nml\n";exit;else printf "which encontrado.\n";fi

if [ ${deparr[1]} -ne 0 ]; then printf "$red""El programa python no está instalado y es necesario. Reinstala y vuelve a ejecutar.""$nml";exit;else printf "python encontrado.\n";fi

if [ ${deparr[2]} -ne 0 ]; then printf "$red""El programa git no está instalado y es necesario. Reinstala y vuelve a ejecutar.""$nml";exit;else printf "git encontrado.\n";fi

if [ ${deparr[3]} -ne 0 ]; then printf "$red""El programa figlet no está instalado y es necesario. Reinstala y vuelve a ejecutar.""$nml";exit;else printf "figlet encontrado.\n";fi

if [ ${deparr[4]} -ne 0 ]; then printf "$red""El programa wget no está instalado y es necesario. Reinstala y vuelve a ejecutar.""$nml";exit;else printf "wget encontrado.\n";fi


############################################################################################

#########################################Chequeo de archivos################################

printf "Chequeando archivos...\n"

if [ -d inter ]; then

	cd inter
	#chequeo de archivos en inter
	printf "$red""Entrando en inter.""$nml\n"
	#chequea si existe index

else

	printf "\n$red""La carpeta inter no existe y es esencial para el funcionamiento de Eash. Para continuar usando Eash es necesario descargar la carpeta inter, el peso aproximado es de Xmb\n""$nml";
	printf "¿Desea descargarla?(y/n) ";

	while true; do

		read choice;

		if [ "$choice" == "y" ]; then

			echo;echo;

			mkdir inter
			printf "Directorio inter creado.\n"
			printf "$red""Entrando en inter.""$nml\n"
			cd inter
			printf "Obteniendo lista de archivos...\n"
			
			#Obtener lista de archivos
			wget $inter/index &> /dev/null

			#Reintentar obtener lista de archivos si es que falla.
			if [ "$?" -ne 0 ]; then 

				printf "Error, reintentando...\n";
				sleep 5;
				wget $inter/index &> /dev/null;

				#Si falla al reintentar, sale.
				if [ "$?" -ne 0 ]; then

					printf "$red""Error al obtener la lista de archivos, saliendo...""$nml\n";

				fi
			fi

			for i in $(cat index); do
				printf "Descargando $i\n"
				wget $inter/$i &> /dev/null;
			done

			printf "Archivos descargados.\n"

			break

		elif [ "$choice" == "n" ]; then

			printf "La carpeta es necesaria. Saliendo...\n"
			exit

		fi
	done
fi

while true; do
if [ -f "index" ]; then
	for i in $(cat index); do
		find "$i" &> /dev/null
		if [ "$?" -ne 0 ]; then

			printf "$red""Faltan archivos importantes, el programa no puede continuar.""$nml\n"
			printf "¿Deseas descargar los archivos faltantes? (y/n) "

			while true; do
				read choice;
				if [ "$choice" == "y" ]; then
					for i in $(cat index); do
						find "$i" &> /dev/null
						if [ "$?" -ne 0 ]; then
							printf "Falta $i"". Descargando...\n"
							wget $inter/$i &> /dev/null
						fi
					done
					printf "Descarga de archivos terminada.\n"

					break
				elif [ "$choice" == "n" ];then
					printf "Faltan archivos importantes. Saliendo...\n"
					exit
				fi
			done
			break
		else
			printf "$i encontrado.\n"
		fi
	done
	break
else
	printf "$red""El archivo index no existe""$nml\n"
	printf "¿Deseas descargarlo? (y/n) "
	while true; do
		read choice;
		if [ "$choice" == "y" ]; then
			wget $inter/index;
			break
		elif [ "$choice" == "n" ]; then
			printf "Falta el archivo index, no puede realizarse la comprobación. Saliendo...\n"
			exit
		fi
	done
	continue
fi
done
printf "Chequeo de archivos concluido.\n"
#############################################################################################

###################################Chequeo de configuración##################################

printf "Chequeando configuración.\n"
pcd=$PWD
conf=0
OS="null"
pack="null"
while true; do

	if [ $conf == 1 ]; then
		printf "Ajustes no encontrados, procediendo...\n";
		#deteccion del sistema
		printf "Intentando detectar el sistema.\n";
		which hostnamectl &> /dev/null; if [ $? -ne 0 ]; then omit=1; else omit=0;fi
		if [ $omit == 0 ]; then
			hostnamectl | grep Arch &> /dev/null;if [ "$?" == 0 ]; then OS="Arch";fi
			hostnamectl | grep Debian &> /dev/null;if [ "$?" == 0 ]; then OS="Debian";fi
			hostnamectl | grep Ubuntu &> /dev/null;if [ "$?" == 0 ]; then OS="Ubuntu";fi
			hostnamectl | grep Mint &> /dev/null; if [ "$?" == 0 ]; then OS="Mint";fi
			hostnamectl | grep Manjaro &> /dev/null; if [ "$?" == 0 ]; then OS="Manjaro";fi
			hostnamectl | grep SUSE &> /dev/null; if [ "$?" == 0 ]; then OS="SUSE";fi
			#hostnamectl | grep Gentoo &> /dev/null; if [ "$?" == 0 ]; then OS="Gentoo";fi
			#hostnamectl | grep Slackware &> /dev/null; if [ "$?" == 0 ]; then OS="Slackware";fi
			hostnamectl | grep Arco &> /dev/null; if [ "$?" == 0 ]; then OS="Arco";fi
			hostnamectl | grep Fedora &> /dev/null; if [ "$?" == 0 ]; then OS="Fedora";fi
			hostnamectl | grep Kali &> /dev/null; if [ "$?" == 0 ]; then OS="Kali";fi
			hostnamectl | grep Parrot &> /dev/null; if [ "$?" == 0 ]; then OS="Parrot";fi
		fi
		#hostnamectl &> /dev/null;
		#if [ "$?" -ne 0 ]; then
		if [ "$omit" == 1 ]; then
			uname -a | grep Android &> /dev/null;
			if [ "$?" == 0 ]; then
				OS="Android"
				printf "Sistema $OS detectado.\n"
				printf "Intentando determinar gestor de paquetes.\n"
				which pkg &> /dev/null;
				if [ "$?" == 0 ]; then 
					pack="pkg";
					printf "Gestor $pack detectado\n";
				else 
					pack="apt";
					printf "Gestor $pack detectado\n";
				fi
			fi
		fi
		unset omit
		if [[ ! "$OS" == "Android" && ! "$OS" == "null" ]]; then
			printf "Sistema $OS detectado.\n";
			printf "Intentando determinar gestor de paquetes.\n";
			case $OS in
			"Arch" | "Manjaro" | "Arco")
				pack="pacman"
			;;
			"Ubuntu" | "Debian" | "Mint" | "Kali" | "Parrot")
				pack="apt"
			;;
			"Fedora")
				which yum &> /dev/null
				if [ $? == 0 ]; then pack="yum"; else pack="dnf";fi
			;;
			"SUSE")
				pack="zypper"
			;;
			esac
			printf "Gestor $pack detectado.\n"
		fi
		if [ "$OS" == "null" ]; then
			while true; do
				printf "No se ha podido detectar el sistema ni el gestor de paquetes.\n"
				printf "Si deseas continuar, especifica el gestor de paquetes: "
				read pack;
				which $pack &> /dev/null;
				if [ "$?" == 0 ]; then
					printf "Gestor $pack detectado\n";
					break;
				else
					printf "Gestor $pack no encontrado.\n"
					continue;
				fi
			done
		fi
		printf "Escribiendo datos en archivos de configuracion.\n";
		cd eash
		echo "$OS" > config;
		echo "$pack" >> config;
		cd ..
		conf=0
		continue
	fi
	cd $pcd
	if [ "$(cat home)" == null ]; then
		printf "No se ha configurado la variable HOME para eash.\n"
		printf "Chequeando que el usuario no sea root...\n"
		if [ $EUID == 0 ]; then
			printf "No se puede completar la configuración de HOME porque el usuario es root. Saliendo...\n"
			cd ..;sudo rm -rf inter
			exit
		fi
		printf "declarando HOME como $HOME\n";
		echo $HOME > home
		continue
	fi
	home=$(cat home)
	cd $home
	if [ ! -d .config ]; then
		mkdir .config;
	fi

	cd $home/.config
	
	if [ ! -d eash ]; then
		mkdir eash
		conf=1
		continue
	fi
	cd eash
	#########COMPROBACION DE ARCHIVOS DE CONFIGURACION##########
	if [ ! -f config ];then
		printf "Falta el archivo config.\n"
		conf=1
		cd $home/.config
		continue
	fi
	if [ ! -f lvl ]; then
		echo null > lvl;
		printf "Archivo lvl creado.\n";
	fi
	#Cargar el archivo config en los primeros dos espacios del array stat
	stat=("null" "null" "null")
	x=0
	for i in $(cat config); do
		stat[$x]=$i
		x=$[x + 1]
	done
	unset x
	#Cargar el contenido de lvl en el último espacio del array stat
	stat[2]=$(cat lvl)
	echo "Configuracion cargada. Valores: ${stat[@]}"
	printf "$green""Finished Test.""$nml\n";
	break
done
