#!/bin/bash

#Amed - Script de edición del bot de Amino.
#Escrito por Darth Venom.
#< = >

#   This file is part hkprogs
#
#   hkprogs is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   hkprogs is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.



uname -a | grep Android &> /dev/null
if [ "$?" == 0 ]; then
	termux=true
else
	termux=false
fi

if ! "$termux"; then
	cd /etc
else
	cd /data/data/com.termux/files/home/.config/hkpac/
fi

out=$(python -c 'import json; import sys;F = open("hkpac.conf","r");d=json.load(F);sys.stdout.write(d["conf"][0]["instdir"])')
cd $out
vim amino
