#!/usr/bin/env python3

import amino
from time import sleep

HackingUtils = "234960818"
GameDevelopers = "1083667"
HarryPotter = "229032048"
Liberales = "196524014"

ChatComun = "18250370-f950-4ada-8510-650511f9f357"
OffRol = "89eaf028-6c6c-419a-bc15-a4216c69b7fe"
CHAT = "03ee80fc-71b4-424e-a9cb-95b89f328a35"
CHTE = "1302adc2-217e-45ef-ac3e-b9e427e6f658"
TiempoLibre = "801c7692-1cca-4702-b25d-2ca04131d113"
Darth = "83e9eb60-3b0e-4009-8b67-dbe432ddae14"
print("Directions declared")
stop = False

ACHAT = CHAT
COMM = HackingUtils

cli = amino.Client()

cli.login("mohamad.bakdounes@hotmail.com", "developer122")
print("Logged in")
sub = amino.SubClient(COMM, cli.profile)
print("Bot online")

old = []
t = []
s = ""

while True:
    msg = sub.get_chat_messages(ACHAT, 2)
    if old == msg.content:
        continue
    for i in msg.content:
        if i in old:
            continue
        if i == None:
            continue

        ############################################ help #############################################
        elif i == "/help":
            print("help :command detected, answering..")
            sub.send_message(ACHAT, "[c]COMMANDS\n\n/hello: Devuelve el saludo\n/hi: devuelve el saludo\n/info [nick]: Revela información sobre un usuario\n/chatId: Devuelve el id del chat\n/commId: Devuelve el id de la comunidad\n/papita: Papita xD\n/comunismo: Sobre el comunismo\n/liberalismo: Sobre el liberalismo\n/public_chats: Muestra los chats públicos de la comunidad\n/goto [chat]: Envía el bot a otro chat\n/mv [comu]: Envía al bot a otra comunidad\n/poweroff: Desconecta el bot\n\n[c]EXCEPTIONS\n\nlackOfArguments: Argumentos insuficientes.")
            continue

        ############################################ hello #############################################
        elif i == "/hello":
            print("hello :command detected, answering: Hello!")
            sub.send_message(ACHAT, "Hello!")
            continue

        ############################################ papita #############################################
        elif i == "/papita":
            print("papita :command detected, answering: Has sido bendecido")
            sub.send_message(ACHAT, "Has sido bendecido")
            continue

        ############################################ hi #############################################
        elif i == "/hi":
            print("hi :command detected, answering: Hi!")
            sub.send_message(ACHAT, "Hi!")
            continue

        ############################################ comunismo #############################################
        elif i == "/comunismo":
            print("comunismo :command detected, answering..")
            sub.send_message(ACHAT, "El comunismo es basura, fomenta el odio, el resentimiento y causó la peor masacre de la historia.\nFuck Marx.")
            continue

        ############################################ liberalismo #############################################
        elif i == "/liberalismo":
            print("liberalismo :command detected, answering..")
            sub.send_message(ACHAT, "El liberalismo es un movimiento e idea que se basa en el respeto irrestricto del proyecto de vida del prójimo.")

        ############################################ chatId #############################################
        elif i == "/chatId":
            print("chatId :command detected, answering: {}".format(ACHAT))
            sub.send_message(ACHAT, "Chat id: {}".format(ACHAT))
            continue

        ############################################ commId #############################################
        elif i == "/commId":
            print("commId :command detected, answering: {}".format(COMM))
            sub.send_message(ACHAT, "Community id: {}".format(COMM))
            continue

        ############################################ Info #############################################
        elif i.startswith("/info "):
            print("info :command detected, procceding.")
            for x in i:
                if x != " ":
                    s += x
                else:
                    t.append(s)
                    s = ""
            t.append(s)
            s = ""
            for x in t[1:]:
                s += x
                s += " "
            t.clear()
            print("Searching for user {}".format(s))
            user = sub.search_users(s)
            print("Done Searching")
            s = ""
            if user.json == []:
                print("User not found")
                sub.send_message(ACHAT, "User not found")
                continue
            for x in user.json[0]:
                s += x
                s += ": "
                s += str(user.json[0][x])
                s += "\n"
            sub.send_message(ACHAT, s)
            print("sending:\n{}".format(s))
            s = ""
            continue
        
        elif i == "/public_chats":
            print("public_chats :command detected, procceding.")
            s = ""
            c = 0
            for x in sub.get_public_chat_threads().title:
                s += "[{}]{}\n".format(c, x)
                c += 1
            sub.send_message(ACHAT, s)
            s = ""
            continue

        ############################################ goto #############################################
        elif i.startswith("/goto "):
            print("goto :command detected, procceding.")
            for x in i:
                if x != " ":
                    s += x
                else:
                    t.append(s)
                    s = ""
            t.append(s)
            print(t)
            s = ""
            ACHAT = sub.get_public_chat_threads().chatId[int(t[1])]
            print(ACHAT)
            sub.join_chat(ACHAT)
            print("Joined")
            t.clear()
            continue

        ############################################ MV #############################################
        elif i.startswith("/mv "):
            print("mv :command detected, procceding.")
            t.clear()
            for x in i:
                if x != " ":
                    s += x
                else:
                    t.append(s)
                    s = ""
            t.append(s)
            s = ""
            print("comm: {}".format(t))
            if t[1] == "HackingUtils":
                COMM = HackingUtils
            elif t[1] == "GameDevelopers":
                COMM = GameDevelopers
            elif t[1] == "HarryPotter":
                COMM = HarryPotter
            else:
                sub.send_message(ACHAT, "Comunidad inexistente.")
                continue
            sub.send_message(ACHAT, "Yendo a {}".format(COMM))
            sub1 = amino.SubClient(COMM, cli.profile)
            #public_chats
            print("public_chats :command detected, procceding.")
            s = ""
            c = 0
            for x in sub1.get_public_chat_threads().title:
                s += "[{}]{}\n".format(c, x)
                c += 1
            c = len(sub1.get_public_chat_threads().title)
            sub.send_message(ACHAT, s)
            s = ""

            sub.send_message(ACHAT, "Selecciona un chat por su número.")
            old1 = []
            ctrl = False
            while True:
                msg = sub.get_chat_messages(ACHAT, 2)
                if old1 == msg.content:
                    continue
                for i in msg.content:
                    if i in old:
                        continue
                    if i == None:
                        continue
    
                    elif i.startswith("/"):
                        i = i[1:]
                        print(i)
                        if int(i) > c:
                            sub.send_message("IndexError. Intenta nuevamente.")
                            continue
                        sub.send_message(ACHAT, "Selected {}".format(i))
                        ACHAT = sub1.get_public_chat_threads().chatId[int(i)]
                        sub1.join_chat(ACHAT)
                        sub = sub1
                        sub.send_message(ACHAT, "I'm here")
                        del sub1
                        ctrl = True
                        break

                old1 = msg.content
                if ctrl == True:
                    break
            del ctrl
            t.clear()
            continue

        ############################################ poweroff #############################################
        elif i == "/poweroff":
            sub.send_message(ACHAT, "Bravo six, going Dark.jpg")
            stop = True
            break

        sleep(1)

    if stop == True:
        break
    old = msg.content
print("Going offline")
cli.logout()
del amino
exit()
