#!/usr/bin/env python3

#   This file is part of hkprogs

#   hkprogs is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.

#   hkprogs is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.

#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

__author__ = "Darth Venom"
__credits__ = ["Darth Venom", "Antitesista"]
__license__ = "GPL"
__maintainer__ = "Darth Venom"

import amino
from getpass import getpass
from tokens import tokenize
from time import sleep
from threading import Thread
from nums import numres
import json
import os
import random
import search
from mod.help import categs, commands
from mod.func import chats
from mod.cmd import params

HackingUtils = "234960818"
GameDevelopers = "1083667"
HarryPotter = "229032048"
Liberales = "196524014"
CyberHacking = "68427685"
CHAT = "03ee80fc-71b4-424e-a9cb-95b89f328a35"
BOT = "23e2ffc7-592a-45dd-a2d8-e54c187a5a2b"
print("Directions declared")

ACHAT = BOT
COMMS = ["HackingUtils", "GameDevelopers", "HarryPotter", "CyberHacking", "DarthVenoms"]
COMM = HackingUtils

cli = amino.Client()

if not "creds" in os.listdir():
    F = open("creds", "w+");creds = {}
    creds["email"]=input("\nintroduce un correo electrónico: ")
    creds["pass"]=getpass("introduce una contraseña: ")
    F.write(json.dumps(creds, indent=4));F.close()
    print("Created creds file")

F = open("creds", "r");creds=json.load(F);F.close()
cli.login(**creds)
print("Logged in")

#Custom commands
if "custom" in os.listdir():
    F = open("custom", "r+")
    custom=json.load(F)
else:
    F = open("custom", "w+")
    custom={}
    F.write(json.dumps(custom, indent=4))
    F.close()
    F = open("custom", "r+")
    custom=json.load(F)

print("Loaded custom commands")

sub = amino.SubClient(COMM, cli.profile)
print("Bot online")

old = []
stop = False
version = "2.2.7"
inum = numres()
Gstop = False
SU = ["83e9eb60-3b0e-4009-8b67-dbe432ddae14", "21cf7113-ab47-4995-b5da-9d6e3f6ba102"]
blkl = ['/eval'] # blacklist

chatT, chatI = chats("HackingUtils", COMMS, sub)

SS = object


def guard():
    global sub
    global ACHAT
    global Gstop
    old = [] #size 15
    print("entering loop:guard")

    while not Gstop:
        msg = sub.get_chat_messages(ACHAT, 15)
        if old == msg.content:
            continue
        print(msg.content)
        for i in range(len(msg.content)):
            if msg.content[i] in old:
                print("inold")
                continue
            if msg.content[i] == None:
                print("isnone")
                E = sub.get_message_info(ACHAT, msg.messageId[i])
                if E.content == "" and E.type == 100:
                    print("deleted message")
                    if old[i] == None:
                        print("Message cannot be restored")
                        continue
                    continue
                if E.content == "" and E.mediaType == 100:
                    print("Image detected")
                    continue
        old = msg.content

####################################################################################################

while True:
    msg = sub.get_chat_messages(ACHAT, 2)
    if old == msg.content:
        if incycle == 25 and not stand and ACHAT != RCHAT:
            try:
                sub.send_message(ACHAT, ">> returned to bots chat", 100)
            except:
                pass
            ACHAT = RCHAT
        if not cmdex:
            incycle += 1
        else:
            cmdex = False
            incycle = 0
        continue

    for i in msg.content:

        if i in old:
            continue
        if i == None:
            continue

        if i.startswith("/") and not "builtin" in blkl:
            print(tokenize(i).full)
            T = tokenize(i); T = T.full

            if T[0] == "/help" and not T[0] in blkl:
                if len(T) == 1:
                    s = "[cb]HackingUtils's Bot\n\n"
                    for x in categs:
                        s += "[b]{}\n".format(x)
                    s += "\n\nPara más información sobre una categoría, pásala como argumento de /help. Si quieres información sobre todas las categorías, usa la opción --all"
                    sub.send_message(ACHAT, s)
                    continue
                if len(T) > 2:
                    sub.send_message(ACHAT, params(excp="too_much_args"))
                    continue
                if T[1] == "--all":
                    s = "[cb]HackingUtils's Bot\n\n"
                    for x in categs:
                        s += "\n[B]{}\n\n".format(x)
                        for e in commands:
                            if x == commands[e][1]:
                                s += "{}: {}\n".format(e, commands[e][0])
                    s += "Escrito por Darth Venom."
                    sub.send_message(ACHAT, s)
                if T[1] in categs:
                    s = "[cb]HackingUtils's bot\n\n[b]{}\n\n".format(T[1])
                    for x in commands:
                        if commands[x][1] == T[1]:
                            s += "{}: {}\n".format(x, commands[x][0])
                    s += "\nEscrito por Darth Venom"
                    sub.send_message(ACHAT, s)
                continue

            if T[0] == "/hello" and not T[0] in blkl:
                x = params(1, 1, sub, T)
                if x != None:
                    sub.send_message(ACHAT, x)
                    continue
                sub.send_message(ACHAT, "Hello!")
                continue

            if T[0] == "/hi" and not T[0] in blkl:
                x = params(1, 1, sub, T)
                if x != None:
                    sub.send_message(ACHAT, x)
                    continue
                sub.send_message(ACHAT, "Hi!")
                continue

            if T[0] == "/version" and not T[0] in blkl:
                x = params(1, 1, sub, T)
                if x != None:
                    sub.send_message(ACHAT, x)
                    continue
                sub.send_message(ACHAT, version)
                continue

            if T[0] == "/di" and not T[0] in blkl:
                x = params(2, 3, sub, T)
                if x != None:
                    sub.send_message(ACHAT, x)
                    continue
                if len(T) == 1:
                    sub.send_message(ACHAT, excp["lack_of_args"])
                    continue
                sub.send_message(ACHAT, T[1].replace('"', ""))
                if len(T) == 3 and T[2] == "--autodel":
                    sub.delete_message(ACHAT, msg.messageId[msg.content.index(i)])
                continue

            if T[0] == "/meme" and not T[0] in blkl:
                x = params(1, 3, sub, T)
                if x != None:
                    sub.send_message(ACHAT, x)
                    continue
                if len(T) == 2:
                    x=search.search(tokenize(T[1].replace('"', '')).full)
                    print(x)
                    if x == "Plantilla no encontrada":
                        sub.send_message(ACHAT, x)
                        continue
                    os.chdir("Meme/Plantillas")
                    x=open(x, "rb")
                    sub.send_message(ACHAT, file=x, fileType="image")
                    x.close()
                    os.chdir("../..")
                if len(T) == 3 and T[2] == "--autodel":
                    sub.delete_message(ACHAT, msg.messageId[msg.content.index(i)])
                    continue
                continue

            if T[0] == "/public_chats" and not T[0] in blkl:
                x = params(1, 1, sub, T)
                if x != None:
                    sub.send_message(ACHAT, x)
                    continue

                s = public_chats(chatT)
                sub.send_message(ACHAT, s)
                continue

            if T[0] == "/info" and not T[0] in blkl:
                x = params(2, 2, sub, T)
                if x != None:
                    sub.send_message(ACHAT, x)
                    continue
                print("Searching for user {}".format(T[1]))
                user = sub.search_users(T[1])
                print("Done Searching")
                if user.json == []:
                    print("User not found")
                    sub.send_message(ACHAT, "User not found")
                    continue
                sub.send_message(ACHAT, """[cb]{}'s info

ID: {}
Publicaciones: {}
Online: {}
Nivel: {}
Reputación: {}

[c]Biografía

{}""".format(user.json[0]["nickname"], user.json[0]["uid"], user.json[0]["blogsCount"], bool(int(user.json[0]["onlineStatus"])), user.json[0]["level"], user.json[0]["reputation"], user.json[0]["content"]))
                continue

            if T[0] == "/goto" and not T[0] in blkl:

                x = params(2, 2, sub, T)
                if x != None:
                    sub.send_message(ACHAT, x)
                    continue
                if not T[1].isdigit():
                    sub.send_message(ACHAT, excp["intbs"])
                    continue
                ACHATT = ACHAT
                ACHAT = chatI[int(T[1])]
                print(ACHAT)
                try:
                    sub.join_chat(ACHAT)
                    print("Joined")
                    sub.delete_message(ACHATT, msg.messageId[msg.content.index(i)])
                    s = "Bot went to {}".format(chatT[int(T[1])])
                except:
                    ACHAT = ACHATT
                    sub.send_message(ACHAT, "Permiso denegado")
                    chatI.pop(int(T[1]))
                    chatT.pop(int(T[1]))
                try:
                    sub.send_message(ACHATT, s, 100)
                except:
                    pass
                continue

            if T[0] == "/mv" and not T[0] in blkl:

                x = params(2, 2, sub, T)
                if x != None:
                    sub.send_message(ACHAT, x)
                    continue

                if T[1] in COMMS:
                    COMM = eval(T[1])
                else:
                    sub.send_message(ACHAT, "Comunidad inexistente.")
                    continue

                sub.send_message(ACHAT, "Yendo a {}".format(COMM))
                sub1 = amino.SubClient(COMM, cli.profile)

                chatT, chatI = chats(COMM, COMMS, sub1)
                s = public_chats(chatT)
                sub.send_message(ACHAT, s)

                sub.send_message(ACHAT, "Selecciona un chat por su número.")
                old1 = []
                ctrl = False
                while True:
                    msg = sub.get_chat_messages(ACHAT, 2)
                    if old1 == msg.content:
                        continue
                    for i in msg.content:
                        if i in old:
                            continue
                        if i == None:
                            continue
        
                        elif i.startswith("/"):
                            i = i[1:]
                            print(i)
                            if not i.isdigit():
                                if i == "back":
                                    del sub1
                                    ctrl = True
                                    break
                                sub.send_message(ACHAT, "Numeric argument expected, got string.")
                                continue
                            if int(i) >= c:
                                sub.send_message(ACHAT, "IndexError. Intenta nuevamente.")
                                continue
                            sub.send_message(ACHAT, "Selected {}".format(i))
                            ACHAT = chatI[int(i)]
                            sub1.join_chat(ACHAT)
                            sub = sub1
                            sub.send_message(ACHAT, "I'm here")
                            del sub1
                            ctrl = True
                            break
                    old1 = msg.content
                    if ctrl == True:
                        break
                del ctrl
                continue

            if T[0] == "/guard" and not T[0] in blkl:

                x = params(2, 2, sub, T)
                if x != None:
                    sub.send_message(ACHAT, x)
                    continue

                if T[1] == "on":

                    try:
                        sub.send_message(ACHAT, "Guard is on", 100)
                    except:
                        pass
                    stand = True
                    Gstop = False
                    GUARD = Thread(target=guard)
                    GUARD.start()

                if T[1] == "off":

                    try:
                        sub.send_message(ACHAT, "Guard is off", 100)
                    except:
                        pass
                    stand = False
                    Gstop = True
                continue

            if T[0] == "/id" and not T[0] in blkl:

                x = params(1, 1, sub, T)
                if x != None:
                    sub.send_message(ACHAT, x)
                    continue

                sub.send_message(ACHAT, "chatId: {}\n\ncomId: {}".format(ACHAT, COMM))
                continue

            if T[0] == "/eval" and not T[0] in blkl:

                x = params(1, 2, sub, T)
                if x != None:
                    sub.send_message(ACHAT, x)
                    continue

                expp = ""
                for i in T[1:]:
                    expp += i
                try:
                    expp = inum.inum(expp)
                    sub.send_message(ACHAT, str(expp))
                except:
                    sub.send_message(ACHAT, "An error ocurred during the operation.")
                    continue
                continue

            if T[0] == "/teach" and not T[0] in blkl:

                x = params(3, 3, sub, T)
                if x != None:
                    sub.send_message(ACHAT, x)
                    continue

                if T[1] == "!":
                    sub.send_message(ACHAT, excp["lack_of_args"])
                    continue
                T[1] = T[1].replace('"', '')
                T[2] = T[2].replace('"', '')
                if T[2].startswith("/di"):
                    sub.send_message(ACHAT,"Using /di on custom commands is not allowed")
                    continue
                if T[2].startswith("!"):
                    sub.send_message(ACHAT,"Using ! on custom commands is not allowed")
                    continue
                custom[T[1]] = T[2]
                F.seek(0);F.truncate()
                F.write(json.dumps(custom, indent=4))
                FCP = open("custom.cp", "w+");FCP.write(json.dumps(custom,indent=4))
                continue

            if T[0] == "/stop" and not T[0] in blkl:
                x = params(1, 1, sub, T)
                if x != None:
                    sub.send_message(ACHAT, x)
                    continue

                sub.delete_message(ACHAT, msg.messageId[msg.content.index(i)])
                stop = True

            if T[0] == "/blkl" and msg.author.userId[msg.content.index(i)] in SU:

                x = params(2, 2, sub, T)
                if x != None:
                    sub.send_message(ACHAT, x)
                    continue

                if T[1] == "list":

                    print(blkl)
                    liscu = ""
                    liscu += "[cb]Black list\n\n"
                    for e in blkl:
                        liscu += "{}\n".format(e)
                    sub.send_message(ACHAT, liscu)

                if T[1] == "add":

                    if len(T) == 2:
                        sub.send_message(ACHAT, excp["lack_of_args"])
                        continue
                    blkl.append(T[2])
                    try:
                        sub.send_message(ACHAT, "Added {}".format(T[2]), 100)
                    except:
                        pass

                if T[1] == "del":

                    if len(T) == 2:
                        sub.send_message(ACHAT, excp["lack_of_args"])
                        continue
                    blkl.pop(blkl.index(T[2]))
                    try:
                        sub.send_message(ACHAT, "Deleted {}".format(T[2]), 100)
                    except:
                        pass
                continue

        if i.startswith("!") and not "custom" in blkl:
            print(tokenize(i).full)
            T = tokenize(i); T = T.full

            if T[0] == "!list":

                liscu = "[cb]Custom commands\n\n"
                for i in custom:
                    liscu += "{}\n".format(i)
                sub.send_message(ACHAT, liscu)
                continue

            if T[0] == "!del":

                x = params(2, 2, sub, T)
                if x != None:
                    sub.send_message(ACHAT, x)
                    continue

                if T[1] in custom:
                    custom.pop(T[1])
                    F.seek(0);F.truncate()
                    F.write(json.dumps(custom, indent=4))
                else:
                    sub.send_message(ACHAT, "Comando inexistente")
                    continue

            if T[0] in custom:

                sub.send_message(ACHAT, custom[T[0]])
                continue

    if stop == True:
        break
    old = msg.content

print("Going offline")
F.close()
cli.logout()
del amino
exit()
